(()=>{let selected=[],previewPhases=[],game=Store.get('activeGame',null),pendingConfirm=null,wakeLock=null;const $=id=>document.getElementById(id);
function nav(id){UI.show(id);if(id==='homeView')renderHomeStats();if(id==='statsView')renderStats();if(id==='libraryView')renderLibrary('all');if(id==='gameView')game?renderGame():UI.show('homeView')}
function savedNames(){return Store.get('players',[])}function persistNames(){Store.set('players',[...new Set([...savedNames(),...selected])])}
function renderSetup(){const names=savedNames();$('savedPlayers').innerHTML=names.map(n=>`<button class="chip" data-add="${n}">+ ${n}</button>`).join('');$('selectedPlayers').innerHTML=selected.map((n,i)=>`<div class="selected-row"><strong>${n}</strong><button class="btn ghost" data-remove="${i}">Fjern</button></div>`).join('')}
function makePreview(){previewPhases=GameEngine.generate($('modeSelect').value,Number($('lengthSelect').value));$('previewList').innerHTML=previewPhases.map((p,i)=>UI.phaseHtml(p,i+1)).join('');$('phasePreview').classList.remove('hidden')}
function addPlayer(name){name=name.trim();if(!name||selected.includes(name))return;selected.push(name);persistNames();renderSetup()}
function renderGame(){if(!game)return;Store.set('activeGame',game);$('roundNo').textContent=game.round;$('starterText').textContent='Starter: '+game.players[(game.round-1)%game.players.length].name;$('undoRoundBtn').disabled=!game.history.length;$('playersGame').innerHTML=game.players.map((p,i)=>{const phase=game.phases[Math.min(p.phaseIndex,game.length-1)],r=game.current[i];return `<article class="player-card"><div class="player-card-accent"></div><div class="player-card-inner"><div class="player-top"><div><div class="player-name">${p.name}</div><div class="phase-label">Fase ${Math.min(p.phaseIndex+1,game.length)} av ${game.length}</div></div><div class="score">${game.usePoints?p.score+' p':'–'}</div></div>${UI.phaseHtml(phase,'').replace('phase-item','phase-item compact')}${r?`<div class="result-done"><span>${r.completed?'✅ Fullført':'❌ Ikke fullført'}${game.usePoints?` · ${r.points} p`:''}</span><button class="edit-btn" data-edit="${i}">Endre</button></div>`:`${game.usePoints?`<label>Poeng<input id="points_${i}" type="number" min="0" inputmode="numeric" value="0"></label>`:''}<div class="result-actions"><button class="btn primary" data-result="${i}:1">Fullført</button><button class="btn secondary" data-result="${i}:0">Ikke fullført</button></div>`}</div></article>`}).join('')}
function warnThreshold(phase){const left=10-GameEngine.phaseCards(phase);if(left<=0)return 0;const theoretical=left*25;const unusual=Math.max(15,Math.round(left*12.5/5)*5);return{left,theoretical,unusual}}
async function askWarning(player,phase,points){const w=warnThreshold(phase);if(!w||points<w.unusual)return true;let text=`Du registrerte ${points} poeng og «Fullført». Fasen bruker ${10-w.left} kort, så spilleren kan bare ha ${w.left} kort igjen. Mente du kanskje «Ikke fullført»?`;if(points>w.theoretical)text=`${points} poeng er høyere enn teoretisk mulig med bare ${w.left} kort igjen. Kontroller registreringen.`;$('dialogTitle').textContent='Er du sikker?';$('dialogText').textContent=text;return new Promise(resolve=>{pendingConfirm=resolve;$('confirmDialog').showModal()})}
async function register(i,completed){const p=game.players[i],phase=game.phases[p.phaseIndex],points=game.usePoints?Number($(`points_${i}`).value||0):0;if(completed&&game.usePoints){const ok=await askWarning(p,phase,points);if(!ok)return}GameEngine.register(game,i,completed,points);renderGame();if(GameEngine.allRegistered(game)){setTimeout(()=>{GameEngine.commitRound(game);Store.set('activeGame',game);if(game.finished)renderFinish();else renderGame()},350)}}
function renderFinish(){const rank=GameEngine.ranking(game);$('winnerTitle').textContent=rank[0].name+' vant!';$('winnerSub').textContent=`${game.round-1} runder · ${game.length} faser`;$('podium').innerHTML=rank.slice(0,3).map((p,i)=>`<div class="podium-item"><div class="podium-name">${p.name}<br><small>${p.score} p</small></div><div class="podium-block place${i+1}">${i+1}.</div></div>`).join('');UI.show('finishView')}

function renderHomeStats(){
  const games=Stats.games(),sum=Stats.summary(),players=Object.entries(sum);
  const totalRounds=games.reduce((a,g)=>a+Math.max(0,(g.round||1)-1),0);
  $('homeStats').innerHTML=`<div class="stat-box"><div class="stat-value">${games.length}</div><div class="stat-label">Spill</div></div><div class="stat-box"><div class="stat-value">${players.length}</div><div class="stat-label">Spillere</div></div><div class="stat-box"><div class="stat-value">${totalRounds}</div><div class="stat-label">Runder</div></div>`;
  if(!players.length){$('homeLeader').innerHTML='<div class="leader-card"><div><strong>Ingen statistikk ennå</strong><div class="leader-meta">Fullfør et spill for å fylle oversikten.</div></div></div>';return}
  const [name,data]=players.sort((a,b)=>b[1].wins-a[1].wins||b[1].games-a[1].games)[0];
  const pct=data.games?Math.round(data.wins/data.games*100):0;
  $('homeLeader').innerHTML=`<div class="leader-card"><div><strong>🏆 ${name} leder</strong><div class="leader-meta">${data.wins} seiere av ${data.games} spill · ${pct} %</div></div><button class="btn ghost" data-nav="statsView">Detaljer</button></div>`;
  $('homeLeader').querySelector('[data-nav]')?.addEventListener('click',()=>nav('statsView'));
}
function renderLibrary(difficulty='all'){
  const list=difficulty==='all'?PHASES:PHASES.filter(p=>Number(p.difficulty)===Number(difficulty));
  $('libraryCount').textContent=`${list.length} faser`;
  $('libraryList').innerHTML=list.map((p,i)=>UI.phaseHtml(p,i+1)).join('')||'<p>Ingen faser i dette filteret.</p>';
  document.querySelectorAll('#libraryFilters [data-difficulty]').forEach(b=>b.classList.toggle('active',String(b.dataset.difficulty)===String(difficulty)));
}
function renderStats(){const games=Stats.games(),sum=Stats.summary();$('statsSummary').innerHTML=`<div class="stat-box"><div class="stat-value">${games.length}</div><div class="stat-label">Spill</div></div><div class="stat-box"><div class="stat-value">${Object.keys(sum).length}</div><div class="stat-label">Spillere</div></div><div class="stat-box"><div class="stat-value">${games.reduce((a,g)=>a+g.round-1,0)}</div><div class="stat-label">Runder</div></div>`;$('playerStats').innerHTML=Object.entries(sum).sort((a,b)=>b[1].wins-a[1].wins).map(([n,s])=>`<div class="stat-row"><div><strong>${n}</strong><div>${s.games} spill · ${(100*s.wins/s.games).toFixed(0)} % seire</div></div><strong>${s.wins} 🏆</strong></div>`).join('')||'<p>Ingen lagrede spill ennå.</p>';$('historyList').innerHTML=games.map(g=>{const r=GameEngine.ranking(g);return `<div class="history-row"><div><strong>${r[0]?.name||'Ukjent'} vant</strong><div>${new Date(g.savedAt).toLocaleDateString('nb-NO')} · ${g.players.map(p=>p.name).join(', ')}</div></div><strong>${g.length} faser</strong></div>`}).join('')||'<p>Ingen historikk ennå.</p>'}
$('newGameBtn').onclick=()=>{selected=[];renderSetup();nav('setupView')};$('continueBtn').onclick=()=>nav('gameView');$('addPlayerBtn').onclick=()=>{addPlayer($('playerInput').value);$('playerInput').value=''};$('playerInput').onkeydown=e=>{if(e.key==='Enter')$('addPlayerBtn').click()};$('savedPlayers').onclick=e=>{if(e.target.dataset.add)addPlayer(e.target.dataset.add)};$('selectedPlayers').onclick=e=>{if(e.target.dataset.remove!==undefined){selected.splice(Number(e.target.dataset.remove),1);renderSetup()}};$('previewBtn').onclick=makePreview;$('startBtn').onclick=()=>{if(selected.length<2)return UI.toast('Velg minst to spillere');if(!previewPhases.length||previewPhases.length!==Number($('lengthSelect').value))makePreview();game=GameEngine.create(selected,$('modeSelect').value,Number($('lengthSelect').value),$('pointsToggle').checked,previewPhases);Store.set('activeGame',game);renderGame();nav('gameView')};$('playersGame').onclick=e=>{const r=e.target.dataset.result;if(r){const [i,c]=r.split(':').map(Number);register(i,!!c)}if(e.target.dataset.edit!==undefined){delete game.current[Number(e.target.dataset.edit)];renderGame()}};$('undoRoundBtn').onclick=()=>{GameEngine.undo(game);renderGame()};$('quitBtn').onclick=()=>{if(confirm('Avslutte spillet uten å lagre?')){Store.remove('activeGame');game=null;nav('homeView')}};$('saveFinishBtn').onclick=()=>{Stats.save(game);Store.remove('activeGame');game=null;UI.toast('Spillet er lagret');nav('statsView')};$('newFromFinishBtn').onclick=()=>{Store.remove('activeGame');game=null;selected=[];renderSetup();nav('setupView')};$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({games:Stats.games()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='phase-companion-backup.json';a.click();URL.revokeObjectURL(a.href)};document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));$('confirmDialog').addEventListener('close',()=>{if(pendingConfirm){pendingConfirm($('confirmDialog').returnValue==='confirm');pendingConfirm=null}});$('wakeBtn').onclick=async()=>{try{if(!('wakeLock'in navigator))throw 0;wakeLock=await navigator.wakeLock.request('screen');$('wakeBtn').textContent='✅ Skjerm på'}catch{UI.toast('Ikke støttet i denne nettleseren')}};document.addEventListener('visibilitychange',async()=>{if(wakeLock&&document.visibilityState==='visible')try{wakeLock=await navigator.wakeLock.request('screen')}catch{}});
$('libraryFilters').onclick=e=>{const d=e.target.dataset.difficulty;if(d)renderLibrary(d)};$('continueBtn').classList.toggle('hidden',!game);renderSetup();renderStats();renderHomeStats();nav('homeView')})();
