(()=>{
let selected=[],previewPhases=[],game=Store.get('activeGame',null),pendingConfirm=null,wakeLock=null,libraryDifficulty='all',statTab='players',historyGameId=null;
const $=id=>document.getElementById(id),defaults={wake:false,autoNext:true,warnings:true,minDifficulty:1,maxDifficulty:5};let settings={...defaults,...Store.get('settings',{})};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function saveSettings(){Store.set('settings',settings)}
function nav(id){if(id==='homeView'&&game)id='gameView';UI.show(id);if(id==='homeView')renderHome();if(id==='statsView')renderStats();if(id==='historyView')renderHistory();if(id==='historyDetailView')renderHistoryDetail();if(id==='libraryView')renderLibrary();if(id==='settingsView')renderSettings();if(id==='gameView')game?renderGame():UI.show('homeView')}
function savedNames(){return Store.get('players',[])}function persistNames(){Store.set('players',[...new Set([...savedNames(),...selected])])}
function renderSetup(){const names=savedNames();$('savedPlayers').innerHTML=names.map(n=>`<button class="chip" data-add="${esc(n)}">+ ${esc(n)}</button>`).join('');$('selectedPlayers').innerHTML=selected.map((n,i)=>`<div class="selected-row"><strong>${esc(n)}</strong><button class="btn ghost" data-remove="${i}">Fjern</button></div>`).join('');renderDifficulty()}
function renderDifficulty(){const show=$('modeSelect').value!=='classic';$('difficultyPicker').classList.toggle('hidden',!show);for(const [id,val,key] of [['minStars',settings.minDifficulty,'minDifficulty'],['maxStars',settings.maxDifficulty,'maxDifficulty']])$(id).innerHTML=[1,2,3,4,5].map(n=>`<button type="button" class="star-btn ${n<=val?'on':''}" data-star-key="${key}" data-star="${n}">★</button>`).join('');$('difficultyLabel').textContent=`${'⭐'.repeat(settings.minDifficulty)}–${'⭐'.repeat(settings.maxDifficulty)}`}
function makePreview(){previewPhases=GameEngine.generate($('modeSelect').value,Number($('lengthSelect').value),settings);$('previewList').innerHTML=previewPhases.map((p,i)=>UI.phaseHtml(p,i+1)).join('');$('phasePreview').classList.remove('hidden')}
function addPlayer(name){name=name.trim();if(!name||selected.includes(name))return;selected.push(name);persistNames();renderSetup()}
function renderGame(){if(!game)return;Store.set('activeGame',game);$('roundNo').textContent=game.round;if(!Number.isInteger(game.starterIndex))game.starterIndex=(game.round-1)%game.players.length;$('starterText').textContent='Starter: '+game.players[game.starterIndex].name;$('undoRoundBtn').disabled=!game.history.length;$('playersGame').innerHTML=game.players.map((p,i)=>{const phase=game.phases[Math.min(p.phaseIndex,game.length-1)],r=game.current[i];return `<article class="player-card"><div class="player-card-accent"></div><div class="player-card-inner"><div class="player-top"><div><div class="player-name">${esc(p.name)}</div><div class="phase-label">Fase ${Math.min(p.phaseIndex+1,game.length)} av ${game.length}</div></div><div class="score">${game.usePoints?p.score+' p':'–'}</div></div>${UI.phaseHtml(phase,'').replace('phase-item','phase-item compact')}${r?`<div class="result-done"><span>${r.completed?'✅ Fullført':'❌ Ikke fullført'}${game.usePoints?` · ${r.points} p`:''}</span><button class="edit-btn" data-edit="${i}">Endre</button></div>`:`${game.usePoints?`<label>Poeng<input id="points_${i}" type="number" min="0" inputmode="numeric" value="0"></label>`:''}<div class="result-actions"><button class="btn primary" data-result="${i}:1">Fullført</button><button class="btn secondary" data-result="${i}:0">Ikke fullført</button></div>`}</div></article>`}).join('')}
function warnThreshold(phase){const left=Math.max(0,10-GameEngine.phaseCards(phase)),thresholds={0:1,1:15,2:25,3:35,4:40,5:45,6:55,7:65,8:75,9:85,10:95};return{left,theoretical:left*25,unusual:thresholds[left]??45}}
async function askWarning(phase,points){if(!settings.warnings)return'confirm';const w=warnThreshold(phase);if(points<w.unusual)return'confirm';$('dialogTitle').textContent=points>w.theoretical?'Kontroller poengsummen':'Virker litt uvanlig';$('dialogText').textContent=points>w.theoretical?`${points} poeng er høyere enn det som normalt er mulig med bare ${w.left} kort igjen. Kontroller om du mente «Ikke fullført».`:`Du registrerte ${points} poeng og valgte «Fullført». Fasen bruker ${10-w.left} kort, så spilleren kan bare ha ${w.left} kort igjen. Mente du kanskje «Ikke fullført»?`;return new Promise(resolve=>{pendingConfirm=resolve;$('confirmDialog').showModal()})}
async function register(i,completed){const p=game.players[i],phase=game.phases[p.phaseIndex],points=game.usePoints?Number($(`points_${i}`).value||0):0;if(completed&&game.usePoints){const choice=await askWarning(phase,points);if(choice==='cancel')return;if(choice==='not-completed')completed=false}GameEngine.register(game,i,completed,points);renderGame();if(GameEngine.allRegistered(game)&&settings.autoNext)setTimeout(()=>{GameEngine.commitRound(game);Store.set('activeGame',game);game.finished?renderFinish():renderGame()},350)}
function renderFinish(){const rank=GameEngine.ranking(game);$('winnerTitle').textContent=rank[0].name+' vant!';$('winnerSub').textContent=`${game.round-1} runder · ${game.length} faser`;$('podium').innerHTML=rank.slice(0,3).map((p,i)=>`<div class="podium-item"><div class="podium-name">${esc(p.name)}<br><small>${p.score} p</small></div><div class="podium-block place${i+1}">${i+1}.</div></div>`).join('');UI.show('finishView')}
function formatDate(d){return new Date(d).toLocaleDateString('nb-NO',{day:'numeric',month:'short',year:'numeric'})}
function renderHome(){const games=Stats.games(),rows=Stats.playerRows(),rounds=games.reduce((a,g)=>a+Math.max(0,(g.round||1)-1),0),leader=rows[0],last=games[0];$('continueBtn').classList.toggle('hidden',!game);$('activeGameCard').classList.toggle('hidden',!game);if(game)$('activeGameCard').innerHTML=`<div><div class="eyebrow">PÅGÅENDE SPILL</div><h2>Runde ${game.round}</h2><p>${game.players.map(p=>`${esc(p.name)} · fase ${Math.min(p.phaseIndex+1,game.length)}`).join(' &nbsp; ')}</p></div><button class="btn primary" id="activeContinue">Fortsett</button>`;$('activeContinue')?.addEventListener('click',()=>nav('gameView'));
$('homeStats').innerHTML=`<div class="dashboard-stat"><span>🎮</span><div><strong>${games.length}</strong><small>Spill</small></div></div><div class="dashboard-stat"><span>👥</span><div><strong>${rows.length}</strong><small>Spillere</small></div></div><div class="dashboard-stat"><span>🔄</span><div><strong>${rounds}</strong><small>Runder</small></div></div><div class="dashboard-stat"><span>🔥</span><div><strong>${leader?Stats.streaks()[leader.name]||0:0}</strong><small>Beste streak</small></div></div>`;
$('lastGame').innerHTML=last?(()=>{const r=GameEngine.ranking(last);return `<button class="history-card plain" data-history-id="${esc(last.id)}"><div><strong>${esc(r[0]?.name||'Ukjent')} vant</strong><div class="leader-meta">${formatDate(last.savedAt||last.created)} · ${last.players.map(p=>esc(p.name)).join(', ')}</div></div><span>${last.length} faser ›</span></button>`})():'<p>Ingen lagrede spill ennå.</p>';
$('homeLeader').innerHTML=rows.length?rows.slice(0,3).map((p,i)=>`<div class="ranking-row"><span class="rank-medal">${['🥇','🥈','🥉'][i]}</span><div><strong>${esc(p.name)}</strong><small>${p.games} spill · ${p.winPct} %</small></div><strong>${p.wins} seiere</strong></div>`).join(''):'<p>Ingen statistikk ennå.</p>'}
function renderLibrary(){const q=$('librarySearch').value.trim().toLowerCase(),type=$('libraryType').value;const list=PHASES.filter(p=>(libraryDifficulty==='all'||Number(p.difficulty)===Number(libraryDifficulty))&&(type==='all'||p.tags.includes(type))&&(!q||p.name.toLowerCase().includes(q)));$('libraryCount').textContent=`${list.length} faser`;$('libraryList').innerHTML=list.map((p,i)=>UI.phaseHtml(p,i+1)).join('')||'<p>Ingen faser i dette filteret.</p>';document.querySelectorAll('#libraryFilters [data-difficulty]').forEach(b=>b.classList.toggle('active',String(b.dataset.difficulty)===String(libraryDifficulty)))}
function renderStats(){const games=Stats.games(),rows=Stats.playerRows(),rounds=games.reduce((a,g)=>a+Math.max(0,(g.round||1)-1),0),streaks=Stats.streaks();$('statsSummary').innerHTML=`<div class="stat-box"><div class="stat-value">${games.length}</div><div class="stat-label">Spill</div></div><div class="stat-box"><div class="stat-value">${rows.length}</div><div class="stat-label">Spillere</div></div><div class="stat-box"><div class="stat-value">${rounds}</div><div class="stat-label">Runder</div></div>`;
$('playerStats').innerHTML=rows.length?`<div class="player-stat-grid">${rows.map(p=>`<article class="player-stat-card"><div class="player-stat-title"><div><h3>${esc(p.name)}</h3><span>${p.games} spill</span></div><div class="win-ring" style="--pct:${p.winPct}"><strong>${p.winPct}%</strong></div></div><div class="metric-grid"><div><strong>${p.wins}</strong><span>Seiere</span></div><div><strong>${p.avgPlace.toFixed(1)}</strong><span>Snittplass</span></div><div><strong>${Math.round(p.avgScore)}</strong><span>Snittpoeng</span></div><div><strong>${streaks[p.name]||0}</strong><span>Beste streak</span></div></div></article>`).join('')}</div>`:'<div class="card"><p>Ingen lagrede spill ennå.</p></div>';
const h=Stats.headToHead();$('h2hStats').innerHTML=h.length?h.map(x=>{const[a,b]=x.players,aw=x.wins[a]||0,bw=x.wins[b]||0;return `<article class="card h2h-card"><div class="h2h-head"><strong>${esc(a)}</strong><span>${x.games} spill</span><strong>${esc(b)}</strong></div><div class="h2h-score"><span>${aw}</span><small>–</small><span>${bw}</span></div><div class="h2h-bar"><i style="width:${x.games?aw/x.games*100:50}%"></i></div></article>`}).join(''):'<div class="card"><p>Head-to-head vises når de samme spillerne har deltatt i lagrede spill.</p></div>';
const groups=Stats.groups();$('groupStats').innerHTML=groups.length?groups.map(g=>{const top=Object.entries(g.wins).sort((a,b)=>b[1]-a[1])[0];return `<article class="card group-card"><div><strong>${g.names.map(esc).join(' + ')}</strong><p>${g.games} spill sammen</p></div><div><strong>${top?esc(top[0]):'–'}</strong><small>${top?top[1]+' seiere':'Ingen vinner'}</small></div></article>`}).join(''):'<div class="card"><p>Ingen spillergrupper ennå.</p></div>';showStatTab(statTab)}
function showStatTab(tab){statTab=tab;document.querySelectorAll('[data-stat-tab]').forEach(b=>b.classList.toggle('active',b.dataset.statTab===tab));$('playerStats').classList.toggle('hidden',tab!=='players');$('h2hStats').classList.toggle('hidden',tab!=='h2h');$('groupStats').classList.toggle('hidden',tab!=='groups')}
function renderHistory(){const games=Stats.games();$('historyList').innerHTML=games.length?games.map(g=>{const r=GameEngine.ranking(g);return `<button class="history-card" data-history-id="${esc(g.id)}"><div><strong>${esc(r[0]?.name||'Ukjent')} vant</strong><div>${formatDate(g.savedAt||g.created)} · ${g.players.map(p=>esc(p.name)).join(', ')}</div></div><span>${Math.max(0,(g.round||1)-1)} runder ›</span></button>`}).join(''):'<p>Ingen historikk ennå.</p>'}
function renderHistoryDetail(){const g=Stats.games().find(x=>x.id===historyGameId);if(!g){nav('historyView');return}const rank=GameEngine.ranking(g);$('historyDetail').innerHTML=`<div class="detail-hero"><div class="trophy">🏆</div><h2>${esc(rank[0]?.name||'Ukjent')} vant</h2><p>${formatDate(g.savedAt||g.created)} · ${g.mode||'spill'} · ${g.length} faser</p></div><div class="final-table">${rank.map((p,i)=>`<div><span>${i+1}. ${esc(p.name)}</span><strong>Fase ${p.phaseIndex} · ${p.score} p</strong></div>`).join('')}</div><h3>Runder</h3><div class="round-list">${(g.history||[]).map(s=>`<details><summary>Runde ${s.round} · startet av ${esc(s.starter||'–')}</summary>${s.results.map(r=>`<div class="round-result"><span>${esc(r.name)}</span><span>${r.completed?'✅ Fullført':'❌ Ikke fullført'} · ${r.points} p</span></div>`).join('')}</details>`).join('')||'<p>Ingen rundedetaljer lagret.</p>'}</div>`}
function renderSettings(){$('wakeToggle').checked=!!settings.wake;$('autoNextToggle').checked=!!settings.autoNext;$('warningToggle').checked=!!settings.warnings;updateWakeButton()}
async function setWake(on){settings.wake=on;saveSettings();if(on){try{if(!('wakeLock'in navigator))throw 0;wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener?.('release',()=>{wakeLock=null;updateWakeButton()})}catch{settings.wake=false;saveSettings();$('wakeToggle').checked=false;UI.toast('Ikke støttet i denne nettleseren')}}else{try{await wakeLock?.release()}catch{}wakeLock=null}updateWakeButton()}
function updateWakeButton(){$('wakeQuickBtn').textContent=settings.wake?'✅ Skjerm på':'☀️ Skjerm av';$('wakeQuickBtn').setAttribute('aria-pressed',String(settings.wake));if($('wakeToggle'))$('wakeToggle').checked=!!settings.wake}
$('newGameBtn').onclick=()=>{selected=[];renderSetup();nav('setupView')};$('continueBtn').onclick=()=>nav('gameView');$('addPlayerBtn').onclick=()=>{addPlayer($('playerInput').value);$('playerInput').value=''};$('playerInput').onkeydown=e=>{if(e.key==='Enter')$('addPlayerBtn').click()};$('savedPlayers').onclick=e=>{if(e.target.dataset.add)addPlayer(e.target.dataset.add)};$('selectedPlayers').onclick=e=>{if(e.target.dataset.remove!==undefined){selected.splice(Number(e.target.dataset.remove),1);renderSetup()}};$('modeSelect').onchange=()=>{previewPhases=[];$('phasePreview').classList.add('hidden');renderDifficulty()};$('difficultyPicker').onclick=e=>{const key=e.target.dataset.starKey,n=Number(e.target.dataset.star);if(!key||!n)return;settings[key]=n;if(settings.minDifficulty>settings.maxDifficulty){if(key==='minDifficulty')settings.maxDifficulty=n;else settings.minDifficulty=n}saveSettings();previewPhases=[];renderDifficulty()};$('previewBtn').onclick=makePreview;$('startBtn').onclick=()=>{if(selected.length<2)return UI.toast('Velg minst to spillere');if(!previewPhases.length||previewPhases.length!==Number($('lengthSelect').value))makePreview();game=GameEngine.create(selected,$('modeSelect').value,Number($('lengthSelect').value),$('pointsToggle').checked,previewPhases,settings);Store.set('activeGame',game);renderGame();nav('gameView')};
$('playersGame').onclick=e=>{const r=e.target.dataset.result;if(r){const[i,c]=r.split(':').map(Number);register(i,!!c)}if(e.target.dataset.edit!==undefined){delete game.current[Number(e.target.dataset.edit)];renderGame()}};$('playersGame').addEventListener('focusin',e=>{if(e.target.matches('input[type=number]')&&e.target.value==='0')e.target.value=''});$('playersGame').addEventListener('focusout',e=>{if(e.target.matches('input[type=number]')&&e.target.value==='')e.target.value='0'});$('undoRoundBtn').onclick=()=>{GameEngine.undo(game);renderGame()};$('quitBtn').onclick=()=>{if(confirm('Avslutte spillet uten å lagre?')){Store.remove('activeGame');game=null;nav('homeView')}};$('saveFinishBtn').onclick=()=>{Stats.save(game);Store.remove('activeGame');game=null;UI.toast('Spillet er lagret');nav('statsView')};$('newFromFinishBtn').onclick=()=>{Store.remove('activeGame');game=null;selected=[];renderSetup();nav('setupView')};
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({schemaVersion:2,games:Stats.games(),players:savedNames()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='phase-companion-backup-v2.5.json';a.click();URL.revokeObjectURL(a.href)};document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));document.addEventListener('click',e=>{const card=e.target.closest('[data-history-id]');if(card){historyGameId=card.dataset.historyId;nav('historyDetailView')}const tab=e.target.closest('[data-stat-tab]');if(tab)showStatTab(tab.dataset.statTab)});$('historyBackBtn').onclick=()=>nav('historyView');$('confirmDialog').addEventListener('close',()=>{if(pendingConfirm){pendingConfirm($('confirmDialog').returnValue||'cancel');pendingConfirm=null}});$('wakeQuickBtn').onclick=()=>setWake(!settings.wake);$('wakeToggle').onchange=e=>setWake(e.target.checked);$('autoNextToggle').onchange=e=>{settings.autoNext=e.target.checked;saveSettings()};$('warningToggle').onchange=e=>{settings.warnings=e.target.checked;saveSettings()};document.addEventListener('visibilitychange',async()=>{if(settings.wake&&document.visibilityState==='visible'&&!wakeLock)try{wakeLock=await navigator.wakeLock.request('screen')}catch{}});$('libraryFilters').onclick=e=>{if(e.target.dataset.difficulty){libraryDifficulty=e.target.dataset.difficulty;renderLibrary()}};$('librarySearch').oninput=renderLibrary;$('libraryType').onchange=renderLibrary;
renderSetup();renderStats();renderHome();renderSettings();updateWakeButton();nav('homeView');if(settings.wake)setWake(true)
})();
