window.GameEngine={
 create(players,mode,length,usePoints,phases,options={}){return{schemaVersion:3,boardId:'local-board',id:crypto.randomUUID?.()||Date.now().toString(),created:new Date().toISOString(),players:players.map(n=>({name:n,phaseIndex:0,score:0,currentStreak:0,streakType:null,bestWinStreak:0,bestMissStreak:0,comebacks:0,leadRounds:0})),mode,length,usePoints,phases,options,round:1,starterIndex:0,current:{},history:[],events:[],finished:false}},
 phaseCards(p){return p.groups.reduce((s,g)=>s+g.length,0)},
 generate(mode,length,options={}){const all=window.PHASES;if(mode==='classic')return all.filter(p=>p.classic).sort((a,b)=>a.classic-b.classic).slice(0,length);const min=Number(options.minDifficulty||1),max=Number(options.maxDifficulty||5);let pool=all.filter(p=>p.difficulty>=min&&p.difficulty<=max);if(mode==='family')pool=pool.filter(p=>p.tags.includes('family')||p.difficulty<=2);if(mode==='hard')pool=pool.filter(p=>p.difficulty>=Math.max(3,min));if(pool.length<length)pool=all.filter(p=>p.difficulty>=min&&p.difficulty<=max);const result=[];let lastTag='';for(let i=0;i<length;i++){const spread=Math.max(1,max-min+1),target=Math.min(max,min+Math.floor(i/(Math.max(1,length/spread))));let optionsList=pool.filter(p=>!result.some(r=>r.id===p.id)&&Math.abs(p.difficulty-target)<=1&&!(lastTag&&p.tags[0]===lastTag&&result.slice(-2).every(r=>r.tags[0]===lastTag)));if(!optionsList.length)optionsList=pool.filter(p=>!result.some(r=>r.id===p.id));if(!optionsList.length)optionsList=pool;const pick=optionsList[Math.floor(Math.random()*optionsList.length)];result.push(pick);lastTag=pick.tags[0]}return result},
 register(game,index,completed,points){game.current[index]={completed,points:Number(points)||0};return game},
 allRegistered(game){return game.players.every((_,i)=>game.current[i])},
 ensure(game){game.events??=[];game.players.forEach(p=>{p.currentStreak??=0;p.streakType??=null;p.bestWinStreak??=0;p.bestMissStreak??=0;p.comebacks??=0;p.leadRounds??=0});return game},
 pushEvent(game,type,text,round=game.round){game.events??=[];game.events.unshift({id:crypto.randomUUID?.()||String(Date.now()+Math.random()),type,text,round,time:new Date().toISOString()});game.events=game.events.slice(0,80)},
 commitRound(game){this.ensure(game);const beforeLeader=this.ranking(game)[0]?.name;const currentStarter=Number.isInteger(game.starterIndex)?game.starterIndex:((game.round-1)%game.players.length);const snapshot={round:game.round,starterIndex:currentStarter,starter:game.players[currentStarter].name,results:[]};game.players.forEach((p,i)=>{const r=game.current[i],missBefore=p.streakType==='miss'?p.currentStreak:0;snapshot.results.push({name:p.name,completed:r.completed,points:r.points,phaseBefore:p.phaseIndex,scoreBefore:p.score,streakBefore:p.currentStreak,streakTypeBefore:p.streakType});p.score+=r.points;if(r.completed&&p.phaseIndex<game.length)p.phaseIndex++;const type=r.completed?'win':'miss';p.currentStreak=p.streakType===type?p.currentStreak+1:1;p.streakType=type;if(type==='win'){p.bestWinStreak=Math.max(p.bestWinStreak,p.currentStreak);if(missBefore>=3){p.comebacks++;this.pushEvent(game,'comeback',`🎉 ${p.name} brøt en bomstreak på ${missBefore}.`)}if(p.currentStreak>=3)this.pushEvent(game,'fire',`🔥 ${p.name} har ${p.currentStreak} fullføringer på rad.`)}else{p.bestMissStreak=Math.max(p.bestMissStreak,p.currentStreak);if(p.currentStreak>=3)this.pushEvent(game,'ice',`${p.currentStreak>=5?'🚨':'❄️'} ${p.name} har bommet ${p.currentStreak} runder på rad.`)}});const candidates=snapshot.results.map((r,i)=>({...r,index:i})).sort((a,b)=>a.points-b.points||(b.completed?1:0)-(a.completed?1:0)||a.index-b.index);game.starterIndex=candidates[0]?.index??0;game.history.push(snapshot);game.current={};game.round++;const newLeader=this.ranking(game)[0]?.name;if(newLeader&&newLeader!==beforeLeader)this.pushEvent(game,'leader',`👑 ${newLeader} tok ledelsen.`,snapshot.round);const leader=this.ranking(game)[0];if(leader){const real=game.players.find(p=>p.name===leader.name);if(real)real.leadRounds++}game.finished=game.players.some(p=>p.phaseIndex>=game.length);return game},
 undo(game){this.ensure(game);const snap=game.history.pop();if(!snap)return game;game.round=snap.round;game.starterIndex=Number.isInteger(snap.starterIndex)?snap.starterIndex:((snap.round-1)%game.players.length);game.current={};snap.results.forEach((r,i)=>{const p=game.players[i];p.score=r.scoreBefore??(p.score-r.points);p.phaseIndex=r.phaseBefore;p.currentStreak=r.streakBefore||0;p.streakType=r.streakTypeBefore||null;game.current[i]={completed:r.completed,points:r.points}});game.events=(game.events||[]).filter(e=>e.round<snap.round);game.finished=false;return game},
 ranking(game){return [...game.players].sort((a,b)=>b.phaseIndex-a.phaseIndex||a.score-b.score)},
 streak(p){return p.currentStreak?{type:p.streakType,count:p.currentStreak}:null},
 timeline(game){const rows={};game.players.forEach(p=>rows[p.name]=[{round:0,phase:0,score:0}]);const phase={},score={};game.players.forEach(p=>{phase[p.name]=0;score[p.name]=0});(game.history||[]).forEach(s=>s.results.forEach(r=>{phase[r.name]+=(r.completed?1:0);score[r.name]+=Number(r.points)||0;rows[r.name].push({round:s.round,phase:phase[r.name],score:score[r.name],completed:r.completed})}));return rows},
 awards(game){const ps=game.players||[],rank=this.ranking(game);const max=(key)=>[...ps].sort((a,b)=>(b[key]||0)-(a[key]||0))[0];return[{icon:'🔥',title:'Lengste fullført-streak',player:max('bestWinStreak'),value:max('bestWinStreak')?.bestWinStreak||0},{icon:'❄️',title:'Lengste bomstreak',player:max('bestMissStreak'),value:max('bestMissStreak')?.bestMissStreak||0},{icon:'🚀',title:'Beste comeback',player:max('comebacks'),value:max('comebacks')?.comebacks||0},{icon:'👑',title:'Ledet flest runder',player:max('leadRounds'),value:max('leadRounds')?.leadRounds||0},{icon:'🏅',title:'Kampens spiller',player:rank[0],value:rank[0]?.score??0}]}
};
