window.GameEngine={
 create(players,mode,length,usePoints,phases,options={}){return{schemaVersion:2,boardId:'local-board',id:crypto.randomUUID?.()||Date.now().toString(),created:new Date().toISOString(),players:players.map(n=>({name:n,phaseIndex:0,score:0})),mode,length,usePoints,phases,options,round:1,starterIndex:0,current:{},history:[],finished:false}},
 phaseCards(p){return p.groups.reduce((s,g)=>s+g.length,0)},
 generate(mode,length,options={}){const all=window.PHASES;if(mode==='classic')return all.filter(p=>p.classic).sort((a,b)=>a.classic-b.classic).slice(0,length);const min=Number(options.minDifficulty||1),max=Number(options.maxDifficulty||5);let pool=all.filter(p=>p.difficulty>=min&&p.difficulty<=max);if(mode==='family')pool=pool.filter(p=>p.tags.includes('family')||p.difficulty<=2);if(mode==='hard')pool=pool.filter(p=>p.difficulty>=Math.max(3,min));if(pool.length<length)pool=all.filter(p=>p.difficulty>=min&&p.difficulty<=max);const result=[];let lastTag='';for(let i=0;i<length;i++){const spread=Math.max(1,max-min+1),target=Math.min(max,min+Math.floor(i/(Math.max(1,length/spread))));let optionsList=pool.filter(p=>!result.some(r=>r.id===p.id)&&Math.abs(p.difficulty-target)<=1&&!(lastTag&&p.tags[0]===lastTag&&result.slice(-2).every(r=>r.tags[0]===lastTag)));if(!optionsList.length)optionsList=pool.filter(p=>!result.some(r=>r.id===p.id));if(!optionsList.length)optionsList=pool;const pick=optionsList[Math.floor(Math.random()*optionsList.length)];result.push(pick);lastTag=pick.tags[0]}return result},
 register(game,index,completed,points){game.current[index]={completed,points:Number(points)||0};return game},
 allRegistered(game){return game.players.every((_,i)=>game.current[i])},
 commitRound(game){const currentStarter=Number.isInteger(game.starterIndex)?game.starterIndex:((game.round-1)%game.players.length);const snapshot={round:game.round,starterIndex:currentStarter,starter:game.players[currentStarter].name,results:[]};game.players.forEach((p,i)=>{const r=game.current[i];snapshot.results.push({name:p.name,completed:r.completed,points:r.points,phaseBefore:p.phaseIndex});p.score+=r.points;if(r.completed&&p.phaseIndex<game.length)p.phaseIndex++});const candidates=snapshot.results.map((r,i)=>({...r,index:i})).sort((a,b)=>a.points-b.points||(b.completed?1:0)-(a.completed?1:0)||a.index-b.index);game.starterIndex=candidates[0]?.index??0;game.history.push(snapshot);game.current={};game.round++;game.finished=game.players.some(p=>p.phaseIndex>=game.length);return game},
 undo(game){const snap=game.history.pop();if(!snap)return game;game.round=snap.round;game.starterIndex=Number.isInteger(snap.starterIndex)?snap.starterIndex:((snap.round-1)%game.players.length);game.current={};snap.results.forEach((r,i)=>{const p=game.players[i];p.score-=r.points;p.phaseIndex=r.phaseBefore;game.current[i]={completed:r.completed,points:r.points}});game.finished=false;return game},
 ranking(game){return [...game.players].sort((a,b)=>b.phaseIndex-a.phaseIndex||a.score-b.score)}
};
